In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [7]:
df.drop([ 'class', 'who', 'adult_male', 'deck', 'embark_town','alive'],axis=1,inplace=True)

In [8]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [9]:
df.dropna(subset="embarked",inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [13]:
df['sex'] = le.fit_transform(df['sex'])

In [14]:
df['embarked'] = le.fit_transform(df['embarked'])

In [15]:
df.astype(int)

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [16]:
X = df.drop('survived',axis = 1)
y = df['survived']

In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [19]:
y_pred = model.predict(X_test)

In [20]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [21]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [23]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [24]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [26]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

### KNN ALGORITHM

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [29]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [34]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [35]:
accuracy_score(y_test,y_pred_knn)

0.7921348314606742

In [36]:
confusion_matrix(y_test,y_pred_knn)

array([[89, 20],
       [17, 52]])

In [37]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178

### Naive bayes

In [39]:
X_train

     pclass  sex        age  sibsp  parch      fare  embarked  alone
708       1    0  22.000000      0      0  151.5500         2   True
240       3    0  29.699118      1      0   14.4542         0  False
382       3    1  32.000000      0      0    7.9250         2   True
792       3    0  29.699118      8      2   69.5500         2  False
683       3    1  14.000000      5      2   46.9000         2  False
..      ...  ...        ...    ...    ...       ...       ...    ...
107       3    1  29.699118      0      0    7.7750         2   True
271       3    1  25.000000      0      0    0.0000         2   True
862       1    0  48.000000      0      0   25.9292         2   True
436       3    0  21.000000      2      2   34.3750         2  False
103       3    1  33.000000      0      0    8.6542         2   True

[711 rows x 8 columns]

In [41]:
X_train_scaled

array([[-1.58410418, -1.40530972, -0.59963554, ...,  2.43059683,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.01249955, ..., -0.35813533,
        -1.95246446, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.16296612, ..., -0.49094895,
         0.58770431,  0.81076671],
       ...,
       [-1.58410418, -1.40530972,  1.38312878, ..., -0.12471679,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.67589571, ...,  0.04708333,
         0.58770431, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.23922629, ..., -0.47611594,
         0.58770431,  0.81076671]])

In [38]:
from sklearn.naive_bayes import GaussianNB

In [42]:
modle_nb = GaussianNB()

In [43]:
modle_nb.fit(X_train,y_train)

GaussianNB()

In [44]:
y_pred_nb = modle_nb.predict(X_test)

In [45]:
y_pred_nb

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [46]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [47]:
accuracy_score(y_test,y_pred_nb)

0.7752808988764045

In [48]:
confusion_matrix(y_test,y_pred_nb)

array([[84, 25],
       [15, 54]])

In [49]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

### DECISION TREE

In [50]:
from sklearn.tree import DecisionTreeClassifier

In [51]:
model_dt = DecisionTreeClassifier(random_state = 42)

In [52]:
model_dt.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [53]:
y_pred_dt = model_dt.predict(X_test_scaled)

In [54]:
accuracy_score(y_test,y_pred_dt)

0.7528089887640449

In [55]:
confusion_matrix(y_test,y_pred_dt)

array([[87, 22],
       [22, 47]])

In [56]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80       109
           1       0.68      0.68      0.68        69

    accuracy                           0.75       178
   macro avg       0.74      0.74      0.74       178
weighted avg       0.75      0.75      0.75       178

In [57]:
from sklearn.svm import SVC

In [58]:
model_svc = SVC(kernel='rbf')

In [59]:
model_svc.fit(X_train_scaled,y_train)

SVC()

In [63]:
y_pred_svc= model_svc.predict(X_test_scaled)

In [64]:
accuracy_score(y_test,y_pred_svc)

0.8258426966292135

In [66]:
confusion_matrix(y_test,y_pred_svc)

array([[96, 13],
       [18, 51]])

In [67]:
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178